### ISSUE TITLE
Failure queue failure.

### ISSUE THREAD

**Issue by docktermj** [Senzing/stream-loader#160]
**Describe the bug**

This bug happens with `SENZING_RABBITMQ_FAILURE_QUEUE` processing.

```console
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pika/adapters/utils/io_services_utils.py", line 1097, in _on_socket_writable
    self._produce()
  File "/usr/local/lib/python3.7/dist-packages/pika/adapters/utils/io_services_utils.py", line 820, in _produce
    self._tx_buffers[0])
  File "/usr/local/lib/python3.7/dist-packages/pika/adapters/utils/io_services_utils.py", line 79, in retry_sigint_wrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pika/adapters/utils/io_services_utils.py", line 861, in _sigint_safe_send
    return sock.send(data)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**To Reproduce**

1. Run https://github.com/Senzing/docker-compose-demo/tree/master/docs/docker-compose-rabbitmq-postgresql-advanced
1. Use
```
export SENZING_DOCKER_COMPOSE_FILE=resources/postgresql/docker-compose-rabbitmq-postgresql-redoer-rabbitmq-withinfo.yaml
```

1. While running use RabbitMQ webapp (http://localhost:15672) to add the following messages to the queue:

Malformed-JSON (see "Delhi""")

```json
{"SOCIAL_HANDLE": "flavorh", "DATE_OF_BIRTH": "4/8/1983", "ADDR_STATE": "LA", "ADDR_POSTAL_CODE": "71232", "SSN_NUMBER": "053-39-3251", "ENTITY_TYPE": "TEST", "GENDER": "F", "srccode": "MDMPER", "CC_ACCOUNT_NUMBER": "5534202208773608", "RECORD_ID": "386820964", "DSRC_ACTION": "A", "ADDR_CITY": "Delhi""", "DRIVERS_LICENSE_STATE": "DE", "PHONE_NUMBER": "225-671-0796", "NAME_LAST": "SEAMAN", "entityid": "284430058", "ADDR_LINE1": "772 Armstrong RD"}
```

Bad DATA_SOURCE value

```json
{"DATA_SOURCE": "BAD_DATA_SOURCE", "ADDR_STATE": "CA", "ADDR_POSTAL_CODE": "90012", "SSN_NUMBER": "202-09-1656", "NAME_FIRST": "JESSICA", "ENTITY_TYPE": "TEST", "GENDER": "F", "srccode": "MDMPER", "CC_ACCOUNT_NUMBER": "374561958104783", "RECORD_ID": "399059018", "DSRC_ACTION": "A", "ADDR_CITY": "Los Angles", "DRIVERS_LICENSE_NUMBER": "419243052", "DRIVERS_LICENSE_STATE": "KO", "PHONE_NUMBER": "213-862-0665", "NAME_LAST": "WHITE", "entityid": "287489572", "ADDR_LINE1": "2292 1st ST"}
```

1. Once they are processed by stream-loader.py, errors will show in the stream-loader.py log

**Comment by docktermj** [comment]
After a while, the docker-compose stack does seem to work.  So it's possible that this really isn't an issue.    But, I think we should still take a look at it to see if there's something that can be improved.

**Comment by jeffadair** [comment]
This failure mode is orthogonal to the record contents. Both correct and malformed records fail in the same way.

This looks like the heartbeat timeout. I'll look into how that works and export it as a settable env var if appropriate.

**Comment by jeffadair** [comment]
Exposed heartbeat as SENZING_RABBITMQ_HEARTBEAT_IN_SECONDS
